# Generated by Django 4.2.6 on 2023-11-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_collection_media_meta_data_tags_varient_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.meta_data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.varient'),
        ),
    ]
